##### Installing Pandas Library

In [175]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.2.1)
Requirement already satisfied: numpy<2,>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.25.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.4)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [176]:
import pandas as pd

In [177]:
pd.__version__

'1.5.3'

In [178]:
pip install --upgrade pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.2.1)
Requirement already satisfied: numpy<2,>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.25.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.4)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [179]:
pd.__version__

'1.5.3'

### Creating a DataFrame

In [48]:
data = {"calories":[420, 380, 390],
        "duration" : [50, 45, 45]
}

In [49]:
df = pd.DataFrame(data)

In [50]:
#df = pd.dataframe(data)

In [51]:
print(df)

   calories  duration
0       420        50
1       380        45
2       390        45

In [52]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [53]:
data2 = [[12,22,44], [50,44,12]]

In [54]:
df2 = pd.DataFrame(data2)

In [55]:
print(df2)

    0   1   2
0  12  22  44
1  50  44  12

### Uploading and importing a csv file

In [56]:
df = pd.read_csv("/content/student.csv")

In [57]:
print(df)

    id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
6    7  My John Rob  Fifth    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78    male
9   10     Big John   Four    55  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row   Four    88    male
15  16        Gimmy   Four    88    male
16  17        Tumyu    Six    54    male
17  18        Honny   Five    75    male
18  19        Tinny   Nine    18    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow  Seven    88    male
25  26       Crelea  Seven    79    male
26  27     Big Nose  Three    81  female
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

### 2nd Way importing csv

In [58]:
df2 = pd.read_csv("/content/drive/MyDrive/student.csv")

In [59]:
print(df)

    id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
6    7  My John Rob  Fifth    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78    male
9   10     Big John   Four    55  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row   Four    88    male
15  16        Gimmy   Four    88    male
16  17        Tumyu    Six    54    male
17  18        Honny   Five    75    male
18  19        Tinny   Nine    18    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow  Seven    88    male
25  26       Crelea  Seven    79    male
26  27     Big Nose  Three    81  female
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [60]:
df.head()

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

In [61]:
df.head(10)

   id         name  class  mark  gender
0   1     John Deo   Four    75  female
1   2     Max Ruin  Three    85    male
2   3       Arnold  Three    55    male
3   4   Krish Star   Four    60  female
4   5    John Mike   Four    60  female
5   6    Alex John   Four    55    male
6   7  My John Rob  Fifth    78    male
7   8       Asruid   Five    85    male
8   9      Tes Qry    Six    78    male
9  10     Big John   Four    55  female

In [62]:
print(df.head(50))

    id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
6    7  My John Rob  Fifth    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78    male
9   10     Big John   Four    55  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row   Four    88    male
15  16        Gimmy   Four    88    male
16  17        Tumyu    Six    54    male
17  18        Honny   Five    75    male
18  19        Tinny   Nine    18    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow  Seven    88    male
25  26       Crelea  Seven    79    male
26  27     Big Nose  Three    81  female
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [63]:
pd.__version__

'1.5.3'

In [65]:
df.head()

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

In [66]:
df.tail()

    id         name  class  mark  gender
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [67]:
df.tail(3)

    id        name  class  mark  gender
32  33   Kenn Rein    Six    96  female
33  34    Gain Toe  Seven    69    male
34  35  Rows Noump    Six    88  female

In [68]:
# print datatpes for each column
df.dtypes

id         int64
name      object
class     object
mark       int64
gender    object
dtype: object

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      35 non-null     int64
 1   name    35 non-null     object
 2   class   35 non-null     object
 3   mark    35 non-null     int64
 4   gender  35 non-null     object
dtypes: int64(2), object(3)
memory usage: 1.5+ KB

In [70]:
df.columns

Index(['id', 'name', 'class', 'mark', 'gender'], dtype='object')

In [71]:
#how many columns there are in dataset
len(df.columns)

5

In [72]:
# number of rows and columns
df.shape

(35, 5)

In [73]:
# statistical summary
df.describe()

              id       mark
count  35.000000  35.000000
mean   18.000000  74.657143
std    10.246951  16.401117
min     1.000000  18.000000
25%     9.500000  62.500000
50%    18.000000  79.000000
75%    26.500000  88.000000
max    35.000000  96.000000

In [74]:
#std = standart devaation
# if std is greater than mean there are possible outlier on your dataset

In [75]:
?df.shape

In [76]:
?df.head

In [77]:
?df.describe

In [78]:
df.index

RangeIndex(start=0, stop=35, step=1)

In [79]:
df.head()

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

### Subsetting and Selecting Columns and Rows

In [80]:
df.head()

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

In [81]:
#printing names of stutdents
df["name"]

0        John Deo
1        Max Ruin
2          Arnold
3      Krish Star
4       John Mike
5       Alex John
6     My John Rob
7          Asruid
8         Tes Qry
9        Big John
10         Ronald
11          Recky
12            Kty
13           Bigy
14       Tade Row
15          Gimmy
16          Tumyu
17          Honny
18          Tinny
19         Jackly
20     Babby John
21         Reggid
22          Herod
23      Tiddy Now
24       Giff Tow
25         Crelea
26       Big Nose
27      Rojj Base
28    Tess Played
29      Reppy Red
30    Marry Toeey
31      Binn Rott
32      Kenn Rein
33       Gain Toe
34     Rows Noump
Name: name, dtype: object

In [83]:
# print first 5 names
df["name"].head()

0      John Deo
1      Max Ruin
2        Arnold
3    Krish Star
4     John Mike
Name: name, dtype: object

In [87]:
# random selection
df["name"].sample()

25    Crelea
Name: name, dtype: object

In [88]:
# random selection
df["name"].sample(5)

23    Tiddy Now
4     John Mike
22        Herod
10       Ronald
25       Crelea
Name: name, dtype: object

In [94]:
# Whats the average mark for first 10 students?
df["mark"].head(10).mean()

68.6

In [95]:
# pick 5 highest marks
?df.nlargest

In [101]:
print(df.nlargest(5, "mark"))

    id       name  class  mark  gender
32  33  Kenn Rein    Six    96  female
11  12      Recky    Six    94  female
31  32  Binn Rott  Seven    90  female
10  11     Ronald    Six    89  female
12  13        Kty  Seven    88  female

In [102]:
df["mark"].nlargest(5)

32    96
11    94
31    90
10    89
12    88
Name: mark, dtype: int64

In [ ]:
# Print info about students with 5 lowest mark.

In [103]:
df.nsmallest(5,"mark")

    id       name  class  mark  gender
18  19      Tinny   Nine    18    male
16  17      Tumyu    Six    54    male
2    3     Arnold  Three    55    male
5    6  Alex John   Four    55    male
9   10   Big John   Four    55  female

In [104]:
# selecting 2 columns

In [108]:
df[["name", "class"]].tail()

           name  class
30  Marry Toeey   Four
31    Binn Rott  Seven
32    Kenn Rein    Six
33     Gain Toe  Seven
34   Rows Noump    Six

In [110]:
df[["id", "name", "gender"]].head()

   id        name  gender
0   1    John Deo  female
1   2    Max Ruin    male
2   3      Arnold    male
3   4  Krish Star  female
4   5   John Mike  female

In [112]:
#this method works only if there is no space in column name. It also doesnt work when column name is reserved keyword

In [113]:
df.name.head()

0      John Deo
1      Max Ruin
2        Arnold
3    Krish Star
4     John Mike
Name: name, dtype: object

In [115]:
df.class
#becuase class is reserved keyword. It wont let you select
df["class"]

SyntaxError: invalid syntax (<ipython-input-115-95bfecf89016>, line 1)

In [116]:
df.name.head()

0      John Deo
1      Max Ruin
2        Arnold
3    Krish Star
4     John Mike
Name: name, dtype: object

In [118]:
# how to print 1st name of the student
df.name[0]

'John Deo'

In [121]:
# df[["name", "class"]][0]
#it requires loc method

In [123]:
df.name[1:3]
#this code will print only 2 elements 3-1= 2

1    Max Ruin
2      Arnold
Name: name, dtype: object

In [124]:
df.name[1:4]

1      Max Ruin
2        Arnold
3    Krish Star
Name: name, dtype: object

In [129]:
df.name[1][0:3]

'Max'

In [131]:
df.name[[1,15,20]]

1       Max Ruin
15         Gimmy
20    Babby John
Name: name, dtype: object

### loc and iloc methods

In [141]:
df.loc[:,"name"]

0        John Deo
1        Max Ruin
2          Arnold
3      Krish Star
4       John Mike
5       Alex John
6     My John Rob
7          Asruid
8         Tes Qry
9        Big John
10         Ronald
11          Recky
12            Kty
13           Bigy
14       Tade Row
15          Gimmy
16          Tumyu
17          Honny
18          Tinny
19         Jackly
20     Babby John
21         Reggid
22          Herod
23      Tiddy Now
24       Giff Tow
25         Crelea
26       Big Nose
27      Rojj Base
28    Tess Played
29      Reppy Red
30    Marry Toeey
31      Binn Rott
32      Kenn Rein
33       Gain Toe
34     Rows Noump
Name: name, dtype: object

In [143]:
df.loc[1:5,"mark"]
# stopping point will be included

1    85
2    55
3    60
4    60
5    55
Name: mark, dtype: int64

In [144]:
df.loc[[1,3,5], ["name", "id"]]

         name  id
1    Max Ruin   2
3  Krish Star   4
5   Alex John   6

In [146]:
#this will print entire dataframe
df.loc[:]

    id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
6    7  My John Rob  Fifth    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78    male
9   10     Big John   Four    55  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row   Four    88    male
15  16        Gimmy   Four    88    male
16  17        Tumyu    Six    54    male
17  18        Honny   Five    75    male
18  19        Tinny   Nine    18    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow  Seven    88    male
25  26       Crelea  Seven    79    male
26  27     Big Nose  Three    81  female
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [151]:
df.head()

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

In [152]:
# how to select data using iloc
# df.loc[[1,3,5], ["name", "id"]]
df.iloc[[1,3,5] ,[1,0]]

         name  id
1    Max Ruin   2
3  Krish Star   4
5   Alex John   6

In [157]:
# how to get index number for name column
df.columns.get_loc("name")

1

In [163]:
?df.columns.get_loc

In [159]:
df.iloc[[1,3,5] ,[df.columns.get_loc("name"),0]]

         name  id
1    Max Ruin   2
3  Krish Star   4
5   Alex John   6

In [164]:
df.iloc[[1,3,5] ,[df.columns.get_loc("name"),df.columns.get_loc("id")]]

         name  id
1    Max Ruin   2
3  Krish Star   4
5   Alex John   6

In [167]:
print(df.iloc[0:6, 1:3])

         name  class
0    John Deo   Four
1    Max Ruin  Three
2      Arnold  Three
3  Krish Star   Four
4   John Mike   Four
5   Alex John   Four

### Missing values

In [168]:
df.isnull()

       id   name  class   mark  gender
0   False  False  False  False   False
1   False  False  False  False   False
2   False  False  False  False   False
3   False  False  False  False   False
4   False  False  False  False   False
5   False  False  False  False   False
6   False  False  False  False   False
7   False  False  False  False   False
8   False  False  False  False   False
9   False  False  False  False   False
10  False  False  False  False   False
11  False  False  False  False   False
12  False  False  False  False   False
13  False  False  False  False   False
14  False  False  False  False   False
15  False  False  False  False   False
16  False  False  False  False   False
17  False  False  False  False   False
18  False  False  False  False   False
19  False  False  False  False   False
20  False  False  False  False   False
21  False  False  False  False   False
22  False  False  False  False   False
23  False  False  False  False   False
24  False  False  False  False   False
25  False  False  False  False   False
26  False  False  False  False   False
27  False  False  False  False   False
28  False  False  False  False   False
29  False  False  False  False   False
30  False  False  False  False   False
31  False  False  False  False   False
32  False  False  False  False   False
33  False  False  False  False   False
34  False  False  False  False   False

In [169]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      35 non-null     int64
 1   name    35 non-null     object
 2   class   35 non-null     object
 3   mark    35 non-null     int64
 4   gender  35 non-null     object
dtypes: int64(2), object(3)
memory usage: 1.5+ KB

In [170]:
# Number of missing values per column
df.isnull().sum()

id        0
name      0
class     0
mark      0
gender    0
dtype: int64

In [172]:
# total number rows with missing values entire dataset
df.isnull().sum().sum()

0

In [174]:
# remove missing values
df.dropna()

    id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
6    7  My John Rob  Fifth    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78    male
9   10     Big John   Four    55  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row   Four    88    male
15  16        Gimmy   Four    88    male
16  17        Tumyu    Six    54    male
17  18        Honny   Five    75    male
18  19        Tinny   Nine    18    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow  Seven    88    male
25  26       Crelea  Seven    79    male
26  27     Big Nose  Three    81  female
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

### Filtering

In [183]:
# Filter students with marks less than 65
df["mark"]<65

0     False
1     False
2      True
3      True
4      True
5      True
6     False
7     False
8     False
9      True
10    False
11    False
12    False
13    False
14    False
15    False
16     True
17    False
18     True
19    False
20    False
21     True
22    False
23    False
24    False
25    False
26    False
27    False
28     True
29    False
30    False
31    False
32    False
33    False
34    False
Name: mark, dtype: bool

In [187]:
# Filter students with marks less than 65
df[df["mark"]<65]

    id         name  class  mark  gender
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
9   10     Big John   Four    55  female
16  17        Tumyu    Six    54    male
18  19        Tinny   Nine    18    male
21  22       Reggid  Seven    55  female
28  29  Tess Played  Seven    55    male

In [188]:
# Use filtering to find info of students in class Nine
df[df["class"]=="Nine"]

    id    name class  mark  gender
18  19   Tinny  Nine    18    male
19  20  Jackly  Nine    65  female

![image.png]()

In [ ]:
# Find the info of students with mark greater than and equal to 90 and in class of Seven

In [192]:
df[(df["class"]=="Seven") & (df["mark"]>=90)]

    id       name  class  mark  gender
31  32  Binn Rott  Seven    90  female

In [193]:
df[(df["mark"]>=90) & (df["class"]=="Seven")]

    id       name  class  mark  gender
31  32  Binn Rott  Seven    90  female

In [ ]:
# Find the info about students where gender is female and class is either Five or Six

![image.png]()

In [ ]:
#1) Write filters seperatly. 3 conditions
#2) df[] write all these conditions inside []. make sure to seperate them using () and & or | symbols

In [194]:
df[(df['gender']=='female') & (df['class']=='Five')]

Empty DataFrame
Columns: [id, name, class, mark, gender]
Index: []

In [195]:
df[(df["gender"]=="female")&((df["class"]=="Six")|(df["class"]=="Five"))]

    id        name class  mark  gender
10  11      Ronald   Six    89  female
11  12       Recky   Six    94  female
29  30   Reppy Red   Six    79  female
32  33   Kenn Rein   Six    96  female
34  35  Rows Noump   Six    88  female

In [196]:
print(df[(df["gender"]=="female")&((df["class"]=="Five")|(df["class"]=="Six"))])

    id        name class  mark  gender
10  11      Ronald   Six    89  female
11  12       Recky   Six    94  female
29  30   Reppy Red   Six    79  female
32  33   Kenn Rein   Six    96  female
34  35  Rows Noump   Six    88  female

![image.png]()